### ISSUE TITLE
一些网址

### ISSUE THREAD

**Issue by guanhui07** [guanhui07/blog#225]
扩展阅读
有哪些鲜为人知，但是很有意思的网站？
一份攻城狮笔记
每天搜集 Github 上优秀的项目
一些有趣的民间故事
超好用的谷歌浏览器、Sublime Text、Phpstorm、油猴插件合集
网站之最
第一个网站（世界上第一个网站）：http://info.cern.ch/
水滴（世界上最小的网站）：http://www.guimp.com/
世界最高（世界上最高的网站）：https://worlds-highest-website.com/
世界最长（世界上最长，增长最快的网站）：http://www.worldslongestwebsite.com/
世界之邮（世界上最长的邮箱）：世界上最长的邮箱
工具类
看图识花（上传图片识别花的种类）：http://stu.iplant.cn/web
Gridzzly（在线制作自己的网格纸）：http://www.gridzzly.com/
在线电子书转换器（电子书格式在线转换）：http://cn.epubee.com/
字体转换器（字体在线转换）：http://www.akuziti.com/
证件照换底色（一键换底色）：https://www.bgconverter.com/
OPEN GPS（高精度 IP 定位）：https://www.opengps.cn/Default.aspx
Windy（在线气象观测）：https://www.windy.com/
RAMMB（全球实时卫星云图）：http://rammb-slider.cira.colostate.edu
ASD 商品历史价格查询（商品价格曲线）：http://asd-price.com/
铁路信息查询（全国铁路车站车次信息查询）：https://moerail.ml/
DesignCap（免费海报在线制作）：https://www.designcap.com/app/
在线工具箱（各种实用工具聚合）：http://tool.mkblog.cn/
在线工具箱（各种实用工具聚合）：http://www.nicetool.net/
长链接生成器：长链接生成器 v2.2
图片/视频工具
Photopea（网页版 PS）：https://www.photopea.com/
PHOTOMOSH（给图片视频加特效）：https://photomosh.com/
Algorithmia（AI 给黑白照片上色）：https://demos.algorithmia.com/colorize-photos/
Remove.bg（在线一键抠图）：https://www.remove.bg/
Nod to the Rhythm（让你的照片张嘴唱歌）：http://nodtotherhythm.com/make
Gfycat（在线制作并托管高清 GIF）：https://gfycat.com/
应景图（GIF 图片添加字幕水印）：http://www.yingjingtu.com/index
极速瘦图（图片压缩）：http://www.jsysuo.com/
Picdiet（图片压缩）：https://www.picdiet.com/zh-cn
TinyPNG（图片压缩）：https://tinypng.com/
Squoosh（图片压缩）：https://squoosh.app/
Needs More JPEG（图片超级压缩）：http://needsmorejpeg.com/
Waifu2x（图片在线无损放大）：http://waifu2x.udp.jp/
Bigjpg（图片放大）：http://bigjpg.com/
ILOVEIMG（在线图片编辑器）：https://www.iloveimg.com
视频解析网（微博，秒拍，快手，抖音）：https://www.parsevideo.com/
IT/AI/工具类
王斌给您对对联（AI 在线对对联）：https://ai.binwang.me/couplet/
玄派网 （武侠生成器）：http://www.xuanpai.com/
Grabient（CSS 代码渐变颜色生成工具）：https://www.grabient.com/
多彩的颜色（图片色彩分析）：https://woshizja.github.io/colorful-color/
Emoji 短网址（把网址变成 Emoji 表情）：https://e.mezw.com/
表情符号生成器（Emoji 表情自定义创建生成）：https://phlntn.com/emojibuilder/
万象智能鉴黄系统（图片分析）：https://cloud.tencent.com/act/event/ci_demo
给小动物加光剑（趣味加工）：https://giphy.com/search/lightsaber-cats
Lyrebird（克隆自己的声音，需登录）：https://lyrebird.ai/signup
Windows93（网页版 windows93 系统）：http://www.windows93.net/
百度镜子（百度的镜子网站）：https://baidujingzi.com/
bilibili 镜子（bilibili 的镜子网站）http://www.ilidilid.com/
ertdfgcvb（代码特效展示）：https://ertdfgcvb.xyz/
Silk（互动生成艺术画）：http://weavesilk.com/
ASCIIFlow Infinity（可视化字符图像绘制）：http://asciiflow.com/
我知道你下载了什么（BT 下载内容监测）：https://iknowwhatyoudownload.com/en/peer/
Foxmiguel（游戏直播聚合站）：http://www.foxmiguel.com/
逗比拯救世界（表情包分享）：http://www.bee-ji.com/
装逼大全（表情包制作）：https://www.zhuangbi.info/
音乐/影视类
穿帮网（影视剧穿帮镜头赏析）：http://www.bug.cn/
The Movie title stills collection（电影标题剧照集）：http://annyas.com/screenshots/
音乐搜索器（音乐聚合搜索下载生成外链）：http://tool.mkblog.cn/music/
资源帝（在线音乐聚合）http://music.ziyuandi.cn/
SUKIER（冷门歌曲推荐）：http://www.sukier.com/
中国摇滚（中国摇滚年代史）：http://www.yaogun.com/
Youtube 字幕下载（字幕下载）：http://downsub.com/
胖鸟电影（最新影视剧蓝光下载站）：http://www.pniao.com/
爱追剧（电视剧电影追剧下载）：http://www.aizhuiju.com/Mov
电影天堂（小体积影视剧下载）：https://www.dygod.net/
高清 MP4ba（最新影视剧下载：复活了）：http://www.mp4ba.com/
RARBG（美国影视 BT 站）：https://rarbgprx.org/torrents.php
动漫花园资源网（动漫作品 BT 下载站）：https://share.dmhy.org/
爱恋动漫（动漫作品 BT 下载站）：http://www.kisssub.org/
迷你 MP4（最新影视剧下载）：http://www.minimp4.com
二次元/动漫类
萌娘百科：https://zh.moegirl.org/Mainpage
神奇宝贝百科：http://wiki.52poke.com/
小鸡词典（互联网流行词汇百科网站）：https://jikipedia.com/
AnimeShot （把动画字幕用于吐槽生活）：https://as2.bitinn.net/
萌兔本地漫画阅读器（漫画本子在线阅读）：http://wusagi.pw/
猫耳 FM（二次元声站）：https://www.missevan.com/
Bilibili 工具箱（弹幕内容查用户名）：https://biliquery.typcn.com/
PaintsChainer（AI 为你的画自动上色）：AI 涂色绘画
文艺类
时间胶囊（封存自己的记忆）：http://p.timepill.net/
时光邮局（给未来的自己写一封信）：https://www.hi2future.com/
I Remember（我记得，一个记忆碎片网站，头脑特工队）：http://i-remember.fr/en/
海の見える駅（能看见海的车站）：https://seaside-station.com/
网盘/搜索类
快速创建收件夹（百度网盘匿名收件箱）：http://xzc.cn/
Firefox Send（临时网盘）：https://send.firefox.com/
Ecosia（搜索引擎，搜索使用的广告收入用于种植树木）：https://www.ecosia.org/
爱搜资源（百度网盘密码破解分享）：https://www.aisouziyuan.com/
鸠摩搜书（电子书搜索下载）：https://www.jiumodiary.com/
GIPHY（GIF 动图搜索网站）：https://giphy.com/
Similar Site Search（相似网站搜索）：https://www.similarsitesearch.com/cn/
文学/百科类
武侠世界（歪果仁翻译中国小说）：https://www.wuxiaworld.com/
维基大典（国学百科）：維基大典
Gallerix（世界名画档案馆）：https://gallerix.ru/
Internet Archive（互联网档案博物馆）：https://archive.org/
世界护照大全（领略全球护照风采）：https://www.passportindex.org/cn/
中国海报（中国历年海报存档）：https://chineseposters.net/
美丽的化学（化学之美）：https://www.beautifulchemistry.net/
乡音苑（中国方言活地图）：http://phonemica.net/
湿在人为（两性博客）：http://www.idashi.org/
汉典（汉字典书）：http://www.zdic.net/
书格（传统书籍）：https://shuge.org/
古诗文网（中国传统古诗文）：https://www.gushiwen.org/
中少快乐阅读平台（怀旧少儿老杂志）：少年儿童杂志全集
实用/行政类
国家邮政局申诉网站（快递问题投诉专用）：http://sswz.spb.gov.cn/
无人认领尸体在线查询（慎入）：http://www.gzbz.com.cn/dead_men/index.asp
药物临床试验登记与信息公示平台（人体实验）：http://www.chinadrugtrials.org.cn/
德州大学电子图书馆（人体骨骼 X 光标本）：http://www.digimorph.org/index.phtml
趣味/无聊类
Spray.training（FPS 游戏压枪训练工具）：http://spray.training/
一键六学（网络梗生成器）：http://bog.ac/tool/6/#
今天中午吃什么？（世纪难题）：https://www.zwcsm.com/
你好污啊（撩妹金句）：https://www.nihaowua.com/
Clash（用歌声说出你想说的话，想起了《大黄蜂》）：https://clash.me/
Windows Update Prank（假装 Windows 升级界面）：http://fakeupdate.net/
字符跳跃（让你的网址动起来）：http://glench.com/hash/#CLICK
happy happy hardcore（治愈小表情）：https://happyhappyhardcore.com/
经典 DVD（无聊网站）：http://itneverhitsthecorner.com/
Neave.TV（稀奇古怪的电视频道）：https://neave.tv/
无聊网站大全（点击进入随机无聊站）：https://theuselessweb.com/
声音/太空类
雨季情绪（下雨的声音）：https://rainymood.com/
VirtOcean（海洋的声音）：http://virtocean.com/
Purrli（猫打呼噜的声音）：https://purrli.com/
这里有猫（Purrli 中文版）：https://m.niucodata.com/cat/cat.php?from=wb
Meteor showers（太空视角观看流星雨）：https://www.meteorshowers.org/
怀旧类
秘密花园（中文网站考古）：http://www.yini.org/
Inspirograph（怀旧在线万花尺）：https://nathanfriend.io/inspirograph/
日本传统色（古典传统配色）：http://nipponcolors.com/
中国色（日本传统色的中文版）：http://zhongguose.com/
四大名著小说（名著地图）：http://www.sdmz.net/
水浒 108 将形象大全（怀旧图片）：http://ls.ganquancun.com/shuihuzhuan108/
游戏/测试类
Am I pretty or ugly?（在线颜值分析）：https://www.prettyscale.com/
MyAccent（测试你的口音是英式还是美式）：口音测试
扫雷（网页版扫雷游戏）：https://www.saolei.org/
信任的进化（人性小游戏）：https://www.sekai.co/trust/
太鼓达人（日本经典音乐游戏网页版）：https://taiko.bui.pm/
一画换一画（互动绘画）：http://www.sketchswap.com/
Lines FRVR（划线小游戏）：https://lines.frvr.com/
Bad News（虚假新闻是怎样炼成的）：https://getbadnews.com/#play
LINE RIDER（Flash 小游戏）：https://www.linerider.com/
QWOP（经典小游戏）：http://www.foddy.net/Athletics.html
Mikutap（鼠标音乐游戏）：https://aidn.jp/mikutap/
Mikutap（鼠标音乐游戏中文版）：https://static.hfi.me/mikutap/
it’s a(door)able（解锁小游戏）：https://ncase.me/door/
ScribblerToo（蜘蛛画画）Scribbler Too
Texter（字符画）：http://tholman.com/texter/
Finding Home（音乐解压游戏）：http://findingho.me/
魔术键盘（解压网站）：http://magickeyboard.io/
Emojis & Earth Porn（寻找不动的表情）：http://emojisandearthporn.com/
Staggering Beauty（精神污染）：http://www.staggeringbeauty.com/
Pica Pic（复古手持游戏合集）：http://www.pica-pic.com/
在线 DOS 游戏（中文怀旧游戏）：https://dos.zczc.cz/
中文家用游戏博物馆（中文怀旧游戏）：http://www.famicn.com/
老男人游戏网（模拟器 ROM 下载网站）：http://www.oldmanemu.net/
Neave Interactive（互动小游戏合集）：https://neave.com/
Bestgames（在线小游戏网站）：http://www.bestgames.com/
IGCD（互联网游戏汽车数据库）：http://www.igcd.net/
Yaksgames (在线免费小游戏站)：https://yaksgames.com/
特别推荐
福利吧（分享你的福利吧）：http://fulibus.net/
龙轩导航（可能是最好用的导航网站）：http://ilxdh.com/
抽屉新热榜（不正经的资讯社区）：https://dig.chouti.com
有趣网址之家（趣味小站集锦）：https://youquhome.com/
科学上网翻墙教程 ：https://sphard2.github.io/gfw

**Comment by xiahibb** [comment]
有意思，谢谢

**Comment by Dongdongdang** [comment]
so good

**Comment by C-Jeril** [comment]
Recommend [kuakua.app](https://kuakua.app), Explore the world of positive psychology and discover how to improve individual and social well-being through scientific methods.
